[package]
name = "krc2lrc"
version = "0.1.3"
edition = "2021"

[package.metadata.winres]
ProductName = "KRC 转 LRC"
CompanyName = "侯坤林"
LegalCopyright = "© 2025 侯坤林. All rights reserved."
InternalName = "krc2lrc"
OriginalFilename = "krc2lrc.exe"
FileDescription = "酷狗音乐 KRC 歌词文件转 LRC 歌词文件程序"

[profile.release]
# https://www.aloxaf.com/2018/09/reduce_rust_size/
#codegen-units = 1
#opt-level = 'z'
#lto = true
#strip = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
winres = "0.1.12"

[dependencies]
flate2 = "1.1.2"
#libflate = "2.0.0"
regex = "1.11.2"
lazy_static = "1.5.0"
console = "0.16.0"
clap = { version = "4.5.46", features = ["derive"] }